In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
t = np.linspace(0,40,1000)

In [3]:
d_r =  2.5 * t
d_s = 3 * (t-5)

In [4]:
# RUN L2 NORM Idea
x =  np.array([25,2,2])
x

array([25,  2,  2])

In [5]:
(25**2 + 2**2 + 2**2)**(1/2)

25.15949125081825

In [6]:
xx =  np.array([25,2,3,4])
xx

array([25,  2,  3,  4])

In [7]:
(25**2 + 2**2 + 3**2 + 4**2)**(1/2)

25.573423705088842

In [8]:
# automatically  do a L2 NORMALIZE  using python library
np.linalg.norm(x)

25.15949125081825

In [9]:
# RUN L1 NORM IDEA
x =  np.array([25.22,-2,2.34])
x

array([25.22, -2.  ,  2.34])

In [10]:
np.abs(25) + np.abs(-2) + np.abs(2)

29

In [11]:
# RUN Squared L2 Norm
x =  np.array([25,2,2])
x

array([25,  2,  2])

In [12]:
np.dot(x,x)

633

In [13]:
# MAX NORM
x =  np.array([25,2,2])
x

array([25,  2,  2])

In [14]:
np.max(x)

25

In [15]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
x[:,1]

array([2, 5])

In [17]:
x[1,:]

array([4, 5, 6])

In [18]:
# REDUCTION


In [19]:
x =  np.array([[2,3],[4,5],[6,7]])
x

array([[2, 3],
       [4, 5],
       [6, 7]])

In [20]:
x.sum()

27

In [21]:
X_torch = torch.asarray([[2,3],[4,5],[6,7]])
X_torch

tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [22]:
torch.sum(X_torch)

tensor(27)

In [23]:
# DOT PRoduct in ML and DL
# Say 2 Vectors
x = np.array([2,3,4])
y =  np.array([4,3,2])

In [24]:
x

array([2, 3, 4])

In [25]:
y

array([4, 3, 2])

In [26]:
np.dot(x,y)

25

In [27]:
XP = np.linspace(-10,10,2000)
XP

array([-10.        ,  -9.989995  ,  -9.97998999, ...,   9.97998999,
         9.989995  ,  10.        ])

In [28]:
#Frebenous NORM

In [29]:
Xfn = np.array([[2,3], [4,5]])
Xfn

array([[2, 3],
       [4, 5]])

In [30]:
np.linalg.norm(Xfn)

7.3484692283495345

In [31]:
Xsym =  np.array([[1,2,3],[4,5,6],[7,8,9]])
Xsym

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
Xsym.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [33]:
Xsym == Xsym.T

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
XidentifyM =  np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
XidentifyM

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [35]:
XidentifyM.T

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [36]:
XidentifyM == XidentifyM.T

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [37]:
Xmat = np.array([2,3,4,5])
Xmat

array([2, 3, 4, 5])

In [38]:
np.dot(XidentifyM, Xmat)

array([2, 3, 4, 5])

In [39]:
Xnew =  np.array([[3,4],[5,60]])
Xnew

array([[ 3,  4],
       [ 5, 60]])

In [40]:
np.linalg.inv(Xnew)

array([[ 0.375  , -0.025  ],
       [-0.03125,  0.01875]])

In [41]:
# X * Xinversion =  Identity Matrix (output)
IdentityM = Xnew * np.linalg.inv(Xnew)

In [42]:
IdentityM

array([[ 1.125  , -0.1    ],
       [-0.15625,  1.125  ]])

In [43]:
IdentityM.T

array([[ 1.125  , -0.15625],
       [-0.1    ,  1.125  ]])

In [44]:
# EIGEN DECOMPOSITION

In [45]:
v = np.array([3,1])
v

array([3, 1])

In [46]:
E =  np.array([[1,0],[0,-1]])
E

array([[ 1,  0],
       [ 0, -1]])

In [47]:
Ev = np.dot(E,v)
Ev

array([ 3, -1])

In [48]:
Ve =  np.dot(v,E)
Ve

array([ 3, -1])

In [49]:
#PRACTISE EIGENVECTOR AND EIGENVALUE

A =  np.array([[2,3],[5,6]])
A

array([[2, 3],
       [5, 6]])

In [50]:
# EIgenVector  -  A X =  Lambda X
Lambdah , X =  np.linalg.eig(A)

In [51]:
Lambdah

array([-0.35889894,  8.35889894])

In [52]:
X

array([[-0.78609474, -0.4266791 ],
       [ 0.61810602, -0.90440309]])

In [53]:
LHS =  np.dot(A, X)
LHS

array([[ 0.28212857, -3.56656746],
       [-0.2218376 , -7.55981402]])

In [54]:
RHS1 =  np.dot(Lambdah[0], X)
RHS1

array([[ 0.28212857,  0.15313468],
       [-0.2218376 ,  0.32458931]])

In [55]:
RHS2 =  np.dot(Lambdah[1], X)
RHS2

array([[-6.57088653, -3.56656746],
       [ 5.16668576, -7.55981402]])

# FROM ABOVE EXAMPLE EigneValue = 1, since from the equ above lhs = rhs

In [56]:
# FROM AOVE EXAMPLE EigneValue = 1, since from the equ above lhs = rhs

# FINDING DETERNMINANT OF A SQUARE MATRIX

In [57]:
#PRACTISE EIGENVECTOR AND EIGENVALUE

A =  np.array([[2,3],[5,6]])
A

array([[2, 3],
       [5, 6]])

In [58]:
DETERMINANT_A = np.linalg.det(A)
DETERMINANT_A

-2.9999999999999982

In [59]:
#DETERMINANT EXAMPLE WITH 3 * 3 MATRIX
b =  np.array([[1,2,3],[-3,5,7],[9,0,3]])
b

array([[ 1,  2,  3],
       [-3,  5,  7],
       [ 9,  0,  3]])

In [60]:
DETERM_B =  np.linalg.det(b)
DETERM_B

24.000000000000014

In [61]:
# comparing eigenvalues and determinant
# DETERMINANT OF MATRIX X = PRODUCT OF LAMBDA OF MATRIX X

lambdaX, Vector = np.linalg.eig(b)
print(lambdaX)
print(Vector)

[ 9.07118585+0.j         -0.03559293+1.62618364j -0.03559293-1.62618364j]
[[ 0.39281292+0.j          0.15261384-0.13840532j  0.15261384+0.13840532j]
 [ 0.71176703+0.j          0.81709013+0.j          0.81709013-0.j        ]
 [ 0.58231066+0.j         -0.52238454+0.13050323j -0.52238454-0.13050323j]]


In [62]:
np.product(lambdaX)

(24.000000000000057+0j)

In [63]:
#EIGENDECOMPOSITION

In [64]:
A =  np.array([[1,2,3,4],[4,5,3,4],[6,7,3,3],[4,2,6,0]])
A

array([[1, 2, 3, 4],
       [4, 5, 3, 4],
       [6, 7, 3, 3],
       [4, 2, 6, 0]])

In [65]:
lam, V = np.linalg.eig(A)

In [66]:
print(lam)

[14.38366247+0.j         -0.24603362+0.j         -2.56881443+1.89048854j
 -2.56881443-1.89048854j]


In [67]:
V

array([[-0.35185444+0.j        ,  0.69821412+0.j        ,
        -0.59035139+0.j        , -0.59035139-0.j        ],
       [-0.53730677+0.j        , -0.59237163+0.j        ,
        -0.02001805+0.19361547j, -0.02001805-0.19361547j],
       [-0.63065517+0.j        , -0.27985208+0.j        ,
         0.50091213+0.21668067j,  0.50091213-0.21668067j],
       [-0.43563052+0.j        ,  0.2885753 +0.j        ,
         0.16103857-0.53833137j,  0.16103857+0.53833137j]])

In [68]:
# eigendecomposition   = V A V-1
# v = vector, v-1 = inverse of vector, A = diagonal matrix
A =  np.array([[2,5],[6,8]])
A

array([[2, 5],
       [6, 8]])

In [69]:
lambdas , V =  np.linalg.eig(A)

In [70]:
lambdas

array([-1.244998, 11.244998])

In [71]:
V

array([[-0.83882686, -0.4757161 ],
       [ 0.54439829, -0.87959888]])

In [72]:
Vminus =  np.linalg.inv(V)
Vminus

array([[-0.8824136 ,  0.4772384 ],
       [-0.54614037, -0.84151111]])

In [73]:
diagonal =  np.diag(A)
diagonal

array([2, 8])

In [74]:
E = np.dot(V, np.dot(diagonal, Vminus))
E

array([7.89382527, 1.7426691 ])

# REAL World Applications of eigendecomposition use cases

In [75]:
# real world eigendecomposition use cases

In [76]:
# SVD for Decomposition EXAMPLE
A = np.array([[3,4],[6,7]])
A

array([[3, 4],
       [6, 7]])

In [77]:
#SVD = U * D * VT
U , D, VT =  np.linalg.svd(A)

In [78]:
# M * M Matrix
U

array([[-0.47630464, -0.87928033],
       [-0.87928033,  0.47630464]])

In [83]:
# M * N Matrix
D2 = np.diag(D)
D2

array([[10.48418432,  0.        ],
       [ 0.        ,  0.28614529]])

In [80]:
# N * N Matrix
VT

array([[-0.63949618, -0.76879427],
       [ 0.76879427, -0.63949618]])

In [85]:
# LHS == RHS
A = np.dot(U, np.dot(D2, VT))
A

array([[3., 4.],
       [6., 7.]])

In [86]:
# SVD for Image Compression
#------------------
from PIL import Image

In [87]:
!wget https://static.scientificamerican.com/sciam/cache/file/4BC816FB-F21A-49C2-A9CB4D85FD64EF69_source.jpg

--2024-09-03 18:47:26--  https://static.scientificamerican.com/sciam/cache/file/4BC816FB-F21A-49C2-A9CB4D85FD64EF69_source.jpg
Resolving static.scientificamerican.com (static.scientificamerican.com)... 151.101.2.49, 151.101.66.49, 151.101.130.49, ...
Connecting to static.scientificamerican.com (static.scientificamerican.com)|151.101.2.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 378480 (370K) [image/jpeg]
Saving to: ‘4BC816FB-F21A-49C2-A9CB4D85FD64EF69_source.jpg’

4BC816FB-F21A-49C2- 100%[===================>] 369.61K  --.-KB/s    in 0.02s   

2024-09-03 18:47:26 (19.4 MB/s) - ‘4BC816FB-F21A-49C2-A9CB4D85FD64EF69_source.jpg’ saved [378480/378480]

